"""
LCEL Runnable Demo
==================
Demonstrates LangChain Expression Language (LCEL) with two chained runnables:
  - Chain 1: Story Creator  (GPT-5.2)  — generates a short story from a topic
  - Chain 2: Content Review (GPT-4o)   — reviews the story for family-friendliness

Flow:  topic → [Story Chain] → story → [Review Chain] → review
"""

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableLambda

from dotenv import load_dotenv

load_dotenv()

# ── Models ────────────────────────────────────────────────────────────────────

story_llm  = ChatOpenAI(model="gpt-5.2", temperature=0.8)   # creative writer
review_llm = ChatOpenAI(model="gpt-4o",  temperature=0.2)   # careful reviewer

# ── Prompts ───────────────────────────────────────────────────────────────────

story_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a creative storyteller who crafts engaging, imaginative short stories."),
    ("human",  "Write a short story (3–4 paragraphs) about: {topic}"),
])

review_prompt = ChatPromptTemplate.from_messages([
    ("system",
     "You are a family content reviewer. Evaluate stories for age-appropriateness.\n"
     "Respond with:\n"
     "  VERDICT: Family-Friendly ✅  or  Not Family-Friendly ❌\n"
     "  REASON:  A brief explanation (2–3 sentences).\n"
     "  SUGGESTIONS: Any recommended edits (or 'None' if already appropriate)."),
    ("human",
     "Please review the following story for family-friendliness:\n\n{story}"),
])

# ── Output parser (shared) ────────────────────────────────────────────────────

parser = StrOutputParser()

# ── Chain 1: Story Creator ────────────────────────────────────────────────────
# Input:  {"topic": str}
# Output: story (str)

story_chain = story_prompt | story_llm | parser

# ── Chain 2: Content Reviewer ─────────────────────────────────────────────────
# Input:  {"story": str}
# Output: review (str)

review_chain = review_prompt | review_llm | parser

# ── Combined pipeline ─────────────────────────────────────────────────────────
# Passes the original topic through alongside the generated story so both are
# available in the final output, then feeds the story into the review chain.
#
# RunnablePassthrough.assign() keeps the current dict and adds a new key.
# The pipe then extracts just the story to pass into review_chain.

full_pipeline = (
    RunnablePassthrough.assign(story=story_chain)       # adds "story" key
    | RunnablePassthrough.assign(                        # adds "review" key
        review=RunnableLambda(lambda x: review_chain.invoke({"story": x["story"]}))
    )
)

# ── Runner ────────────────────────────────────────────────────────────────────

def run_demo(topic: str) -> None:
    print("=" * 60)
    print(f"TOPIC: {topic}")
    print("=" * 60)

    result = full_pipeline.invoke({"topic": topic})

    print("\n📖  STORY  (generated by GPT-5.2)")
    print("-" * 60)
    print(result["story"])

    print("\n🔍  FAMILY-FRIENDLINESS REVIEW  (by GPT-4o)")
    print("-" * 60)
    print(result["review"])
    print()


if __name__ == "__main__":
    run_demo("a young wizard who discovers a hidden library beneath the ocean")
